CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=12231 --use_env run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 50000 \
--save_interval 5000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 425 \
--microbatch 425 \
--hf_dataset cnn_dailymail \
--hf_version 3.0.0 \
--learned_mean_embed True \
--denoise True \
--vocab bert \
--seq_len 1024 \
--use_fp16 \
--denoise_rate 0.5 \
--schedule_sampler lossaware \
--notes "summarization" \